services:
    fastapi:
        public: true
        image: piercesaly/pfgl:hello
        build: .
        replicas: 1
        ports:
            - 8080
        resources:
            cpu: 100m
            memory: 128Mi
